.PHONY: run-dist win-run-dist help win-help build

run-dist:
	./build/install/app/bin/app $(ARGS)

win-run-dist:
	.\build\install\app\bin\app $(ARGS)

help:
	./build/install/app/bin/app -h

win-help:
	.\build\install\app\bin\app -h

build:
	./gradlew build

win-build:
	.\gradlew build