run-dist:
	./build/install/app/bin/app $(ARGS)
	.PHONY: build

win-run-dist:
	.\build\install\app\bin\app $(ARGS)
	.PHONY: build

help:
	./build/install/app/bin/app -h
	.PHONY: build

win-help:
	.\build\install\app\bin\app -h
	.PHONY: build