name: makefile

on: push

defaults:
  run:
    working-directory: app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: Build and install
        run: ./gradlew installDist
      - run: make run-dist ARGS="file1.json file2.json"
      - run: make help
      - run: make build