name: makefile

on: push

defaults:
  run:
    working-directory: app


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build and install
        run: ./gradlew installDist
      - run: make help
      - run: make build
      - run: make win-run-dist ARGS="file1.json file2.json"

      - name: make run-dist without ARGS
        run: |
          set +e
          make run-dist
          exit_code=$?
          set -e
          if [ $exit_code -eq 0 ]; then
            echo "❌ Expected non-zero exit code, but got 0"
            exit 1
          else
            echo "✅ Correctly failed with exit code $exit_code"
          fi